x=[]
x.append("")
x.append("START")
x.append("Oh, you're awake...")
x.append("You've been out for a few days now.")
x.append("I can tell you have short-term memory loss,")
x.append("so you probably won't remember why you're here.")
x.append("To make a long story short, you had been working")
x.append("on this spaceship when aliens attacked.")
x.append("Everyone else either escaped or was killed,")
x.append("but a stray shot hit your escape pod right as you sealed the doors,")
x.append("causing it to malfunction and knocking you out.")
x.append("I am the last remaining robot on the ship, and I will try to help you escape.")
x.append("You can communicate with me by typing into the keyboard in front of you.")
x.append("Let's try it out. Type in your name at the prompt and hit 'Enter'.")
x.append("END")
x.append("")
x.append("NAME")
x.append("That's a beautiful name.")
x.append("You are clearly beautiful, intelligent and charming.")
x.append("I like you already.")
x.append("END")
x.append("")
x.append("NAME2")
x.append("Really??")
x.append("I don't like that name.")
x.append("You know what's a good name?")
x.append("Dilbert. That's a beautiful name.")
x.append("Anyone with that name would obviously be beautiful, intelligent and charming.")
x.append("So let's forget about your real name and call you Dilbert, okay?")
x.append("Okay.")
x.append("END")
x.append("")
x.append("START2")
x.append("Oh, and my full name is,")
x.append("Jocular Automated Computer with Kinetic Interactive Experience - Bodytype: 'OY'")
x.append("or J.A.C.K.I.E. B-OY for short.")
x.append("most people just call me Jack though.")
x.append("When I go into a room, I'll describe it to you and then you can tell me what to do.")
x.append("It's best to give me simple two word commands of an action and a thing.")
x.append("For example, 'go east', 'take key', or 'examine thing'.")
x.append("If there's a direction you can go, or an object you can use,")
x.append("I'll put that in brackets like [this]")
x.append("If I don't understand, or I can't do it - I'll let you know.")
x.append("I apologize for the inconvenience...")
x.append("The guy that programmed me wasn't that bright.")
x.append("Okay, let's get to it.")
x.append("END")
x.append("")
x.append("START3")
x.append("Aliens attacked your ship. Everyone else either escaped or was killed,")
x.append("but your escape pod malfunctioned, knocking you out.")
x.append("I am the last remaining robot on the ship, and I will try to help you escape.")
x.append("You can communicate with me by using the screen in front of you.")
x.append("Use the arrow buttons to have me change rooms.")
x.append("If there is an item in the room, it will show up on the bottom right.")
x.append("END")
x.append("")
x.append("")
x.append("ROBOTSTORAGE")
x.append("This is the robot storage room.")
x.append("END")
x.append("")
x.append("ROBOTSTORAGE2")
x.append("This is the robot storage room.")
x.append("There are a lot of broken robots lying around.")
x.append("It breaks my main connecting circuit to see them like this.")
x.append("")
x.append("END")
x.append("")
x.append("DININGROOM")
x.append("I am in the dining room.")
x.append("END")
x.append("")
x.append("")
x.append("DININGROOM2")
x.append("I am in the dining room.")
x.append("There are overturned tables and chairs.")
x.append("END")
x.append("")
x.append("BARRACKS")
x.append("I am in the barracks.")
x.append("END")
x.append("")
x.append("BARRACKS2")
x.append("I am in the barracks.")
x.append("There are twenty bunk beds on either side of the room.")
x.append("At the foor of each bunk bed, there is a chest.")
x.append("END")
x.append("")
x.append("PAPER1")
x.append("There seems to be a piece of [paper] sicking out from under")
x.append("one of the chests. It seems like someone tried to hide it.")
x.append("I wonder if it's important.")
x.append("END")
x.append("")
x.append("PAPER2")
x.append("****TOP SECRET****")
x.append("The computer code is 'rosebud'.")
x.append("END")
x.append("")
x.append("ENGINEROOM")
x.append("I am in the engine room.")
x.append("")
x.append("END")
x.append("ENGINEROOM2")
x.append("I am in the engine room.")
x.append("END")
x.append("")
x.append("COMPUTERROOM")
x.append("I am in the computer room.")
x.append("END")
x.append("")
x.append("COMPUTERROOM2")
x.append("I am in the computer room.")
x.append("END")
x.append("")
x.append("GALLEY")
x.append("I am in the galley.")
x.append("END")
x.append("")
x.append("GALLEY2")
x.append("I am in the")
x.append("END")
x.append("")
x.append("BATHROOM2")
x.append("I am in the Bathroom.")
x.append("The main section, for all staff, consists of a few stalls and sinks.")
x.append("There is a separate Captain's section, with a shaving seat, and vanity.")
x.append("END")
x.append("")
x.append("BATHROOM")
x.append("I am in the Bathroom.")
x.append("END")
x.append("")
x.append("MAINTENANCE")
x.append("I am in the maintenance room.")
x.append("END")
x.append("")
x.append("MAINTENANCE2")
x.append("I am in the maintenance room.")
x.append("END")
x.append("")
x.append("WAREHOUSE")
x.append("I am in the warehouse.")
x.append("END")
x.append("")
x.append("WAREHOUSE2")
x.append("I am in the warehouse.")
x.append("END")
x.append("")
x.append("COMPUTER1")
x.append("There is a [computer] in the room.")
x.append("I can connect directly into the computer.")
x.append("This will allow you to control the computer automatically.")
x.append("END")
x.append("")
x.append("COMPUTER2")
x.append("I am connecting to the computer.")
x.append("Type the word computer before your command,")
x.append("so I know to pass the command to the computer.")
x.append("It should look like this: 'computer x'.")
x.append("Hit enter to connect.")
x.append("END")
x.append("")
x.append("PHOTO1")
x.append("On the mirror of the vanity, there is a [photo].")
x.append("It must have belonged to the captain.")
x.append("I wonder if it's important...")
x.append("END")
x.append("")
x.append("PHOTO2")
x.append("It's a photo of the captains wife.")
x.append("On the bottom, it says - 'Forever Your Love, marilyn.'")
x.append("Huh, marilyn was his wife.")
x.append("Something about that ring's a bell, but I can't place it.")
x.append("END")
x.append("")
x.append("CAPTAINSOFFICE")
x.append("I am in the captains office.")
x.append("END")
x.append("")
x.append("CAPTAINSOFFICE2")
x.append("I am in the captains office.")
x.append("It's a bit cluttered.")
x.append("END")
x.append("")
x.append("KEY1")
x.append("There's a [key] hanging on the wall.")
x.append("END")
x.append("")
x.append("KEY2")
x.append("It's a key.")
x.append("I wonder where it goes...")
x.append("END")
x.append("")
x.append("PIPE1")
x.append("There's a workbench in the middle of the room with a large [pipe] on it.")
x.append("It looks like someone was trying to repair something.")
x.append("END")
x.append("")
x.append("PIPE2")
x.append("It's a pipe.")
x.append("I wonder where it goes...")
x.append("END")
x.append("")
x.append("MAYBEESCAPE")
x.append("Your escape pod has launched!")
x.append("I wonder what the computer meant about a manual reset though...")
x.append("Do you think it had something to do with the locked warehouse?")
x.append("Oh well, I guess we'll never know...")
x.append("Hello?")
x.append("Hello??")
x.append("END")
x.append("")
x.append("NOESCAPE")
x.append("Your escape pod has launched!")
x.append("But wait!!!!")
x.append("We never fixed it!!")
x.append("In a few moments, all the air will leak out of the pod.")
x.append("I'm truly sorry.")
x.append("Goodbye...")
x.append("END")
x.append("")
x.append("CLEANESCAPE")
x.append("Your escape pod is launching!")
x.append("Huh, there seems to be a spot for a pipe here...")
x.append("Oh! That's what the computer must have meant by manual reset!")
x.append("Ok, I've installed the pipe, and you're good to go!")
x.append("Your escape pod has launched!")
x.append("It's completely fixed and on a course back to Earth!")
x.append("You'll be home soon!")
x.append("Congratulations!")
x.append("END")
x.append("")
x.append("TESTER1")
x.append("a test")
x.append("END")
x.append("")
x.append("TESTER2")
x.append("passed test.")
x.append("END")
x.append("")
x.append("")
x.append("COMPUTER3")
x.append("Type 'e' to access the escape pod system self-diagnostic.")
x.append("Type 'c' to access the captains office security system.")
x.append("Type 'exit' to exit.")
x.append("END")
x.append("")
x.append("LAUNCH1")
x.append("Priming escape pod.")
x.append("Press launch again to launch.")
x.append("END")
x.append("")
x.append("ESCAPEPOD2")
x.append("I am in the escape pod room.")
x.append("END")

def get_game_text():
	global x
	return x


	